# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json
COPY package*.json .

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 5000

# Start node server
CMD ["npm", "start"]